name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Calendar
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        with:
          SETTING_JSON: |
            {
              "githubUserName": "${{ github.repository_owner }}",
              "startForegroundColor": "#a960ee",
              "endForegroundColor": "#ff333d",
              "backgroundColor": "#0d1117",
              "wDayAndMonthFontColor": "#9999ff",
              "laneColor": "#222244",
              "dayVariant": 2
            }

      - name: Push 3D contrib image to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
